=== pkrausee/UG-XML/LAB3/zad.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT glowny (podrzedny, podrzedny, podrzedny, podrzedny, podrzedny+,
                 pierwszy, pierwszy, pierwszy?, drugi, drugi, drugi?,
                 (
                 ((parzysty, parzysty)*)|(nieparzysty, (nieparzysty, nieparzysty)*)
                 )
                 )> 

<!ELEMENT podrzedny ANY>
<!ELEMENT pierwszy ANY>
<!ELEMENT drugi ANY>
<!ELEMENT parzysty ANY>
<!ELEMENT nieparzysty ANY>

=== pkrausee/UG-XML/LAB3/zad.xml
<?xml version='1.0' encoding='ISO-8859-2'?>
<!DOCTYPE glowny SYSTEM "zad.dtd">
<glowny>

	<podrzedny></podrzedny>
	<podrzedny></podrzedny>
	<podrzedny></podrzedny>
	<podrzedny></podrzedny>
	<podrzedny></podrzedny>

	<pierwszy></pierwszy>
	<pierwszy></pierwszy>
	<pierwszy></pierwszy>

	<drugi></drugi>
	<drugi></drugi>

	<parzysty></parzysty>
	<parzysty></parzysty>

</glowny>
