=== pkrausee/UG-XML/LAB3/zad6.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!ELEMENT zamowienie (adres, artykuly)> 
<!ATTLIST zamowienie numer_zamowienia ID #REQUIRED>

<!ELEMENT adres (miejsce, ulica?, kod_pocztowy)>
<!ATTLIST adres termin_dostarczenia CDATA #IMPLIED>
<!ATTLIST adres kraj CDATA #FIXED "Polska">

<!ELEMENT artykuly (artykul+)>

<!ELEMENT artykul (film|ksiazka|plyta)>
<!ATTLIST artykul id ID #REQUIRED>

<!ELEMENT film (tytul, rezyser, rok_wydania, czas_trwania?)>

<!ELEMENT ksiazka (tytul, autor, rok_wydania, nr_wydania)>

<!ELEMENT plyta (tytul, wykonawca, wydawca, rok_wydania, czas_trwania?)>

<!ELEMENT kod_pocztowy (#PCDATA)>
<!ELEMENT rok_wydania (#PCDATA)>
<!ELEMENT nr_wydania (#PCDATA)>
<!ELEMENT czas_trwania (#PCDATA)>
<!ELEMENT rezyser (#PCDATA)>
<!ELEMENT miejsce (#PCDATA)>
<!ELEMENT ulica (#PCDATA)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT wykonawca (#PCDATA)>
<!ELEMENT wydawca (#PCDATA)>
<!ELEMENT autor (#PCDATA)>

=== pkrausee/UG-XML/LAB3/zad6.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE zamowienie SYSTEM "zad6.dtd">
<zamowienie numer_zamowienia="abc123">
    <adres kraj="Polska">
        <miejsce>dom</miejsce>
        <ulica>Jana Bażyńskiego 8</ulica>
        <kod_pocztowy>12-345</kod_pocztowy>
    </adres>
    <artykuly>
        <artykul id="a">
            <film>
                <tytul>Aquaman</tytul>
                <rezyser>Nie wiem</rezyser>
                <rok_wydania>2018</rok_wydania>
                <czas_trwania>spory</czas_trwania>
            </film>
        </artykul>
        <artykul id="b">
            <ksiazka>
                <tytul>Kobieta z wydm</tytul>
                <autor>Abe Kobo</autor>
                <rok_wydania>2010</rok_wydania>
                <nr_wydania>1</nr_wydania>
            </ksiazka>
        </artykul>
        <artykul id="c">
            <plyta>
                <tytul>Chodnikowa</tytul>
                <wykonawca>Ja</wykonawca>
                <wydawca>Pol-Bruk</wydawca>
                <rok_wydania>2019</rok_wydania>
            </plyta>
        </artykul>
    </artykuly>
</zamowienie>
