=== pkrausee/UG-XML/LAB7/zad1.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="szkola">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nauczyciele">
                    <xs:complexType>
                        <xs:sequence>
                           <xs:element ref="osoba" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="uczniowie">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="osoba" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="pozostali">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="osoba" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="osoba">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="imie"/>
                <xs:element type="xs:string" name="nazwisko"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="plec"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== pkrausee/UG-XML/LAB7/zad1.xml
<?xml version="1.0"?>
<szkola xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad1.xsd">
    <nauczyciele>
        <osoba plec="kobieta">
            <imie>Kajetan</imie>
            <nazwisko>Paszkiewicz</nazwisko>
        </osoba>
    </nauczyciele>
    <uczniowie>
        <osoba plec="mezczyzna">
            <imie>Kajetan</imie>
            <nazwisko>Paszkiewicz</nazwisko>
        </osoba>
    </uczniowie>
    <pozostali>
        <osoba plec="kobieta">
            <imie>Kajetan</imie>
            <nazwisko>Paszkiewicz</nazwisko>
        </osoba>
    </pozostali>
</szkola>
