=== pkrausee/UG-XML/lab7/zad2.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="element">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="osoba" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="osoba" />
                        </xs:sequence>
                        <xs:attributeGroup ref="atrybuty" />
                    </xs:complexType>
                </xs:element>

                <xs:element name="adres" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="adres" />
                        </xs:sequence>
                        <xs:attributeGroup ref="atrybuty" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>



    </xs:element>
    <xs:group name="adres">
        <xs:sequence>
            <xs:element name="miejsce" type="xs:string" />
            <xs:element name="ulica" type="xs:string" />
            <xs:element name="kodPocztowy" type="xs:string" />
        </xs:sequence>
    </xs:group>

    <xs:group name="osoba">
        <xs:sequence>
            <xs:element name="imie" type="xs:string" />
            <xs:element name="nazwisko" type="xs:string" />
            <xs:element name="dataUrodzenia" type="xs:string" />
        </xs:sequence>
    </xs:group>

    <xs:attributeGroup name="atrybuty">
        <xs:attribute name="NIP" type="xs:string" />
        <xs:attribute name="pesel" type="xs:string" />
    </xs:attributeGroup>
</xs:schema>

=== pkrausee/UG-XML/lab7/zad2.xml
<?xml version="1.0" encoding="utf-8"?>
<element xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad2.xsd">
    <osoba NIP="str1234" pesel="str1234">
        <imie>str1234</imie>
        <nazwisko>str1234</nazwisko>
        <dataUrodzenia>str1234</dataUrodzenia>
    </osoba>
    <adres NIP="str1234" pesel="str1234">
        <miejsce>str1234</miejsce>
        <ulica>str1234</ulica>
        <kodPocztowy>str1234</kodPocztowy>
    </adres>
</element>
