=== pkrausee/UG-XML/LAB7/zad6.xsd
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="zamowienie">
        <xs:complexType mixed="true">
            <xs:sequence>
                <xs:element name="adres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="miejsce" type="xs:string"/>
                            <xs:element name="ulica" type="xs:string" minOccurs="0"/>
                            <xs:element name="kod_pocztowy" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="termin_dostarczenia" type="xs:string" use="optional"/>
                        <xs:attribute name="kraj" type="xs:string" use="required" fixed="Polska"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="artykuly">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="artykul" minOccurs="1" maxOccurs="100">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:choice>
                                            <xs:element ref="film"/>
                                            <xs:element ref="ksiazka"/>
                                            <xs:element ref="plyta"/>
                                        </xs:choice>
                                        <xs:element ref="ilosc"/>
                                    </xs:sequence>
                                    <xs:attribute name="id" use="required" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="numer_zamowienia" type="xs:string" use="required"/>
        </xs:complexType>

        <xs:unique name="unikat">
            <xs:selector xpath="artykuly/artykul" />
            <xs:field xpath="@id" />
        </xs:unique>

    </xs:element>

    <xs:element name="ilosc" default="1">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="1"/>
                <xs:maxInclusive value="100"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="film">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tytul" type="xs:string"/>
                <xs:element name="rezyser"  type="xs:string"/>
                <xs:element name="rok_wydania" type="xs:string"/>
                <xs:element name="czas_trwania" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ksiazka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tytul" type="xs:string"/>
                <xs:element name="autor" type="xs:string"/>
                <xs:element name="rok_wydania" type="xs:string"/>
                <xs:element name="nr_wydania" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="plyta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="tytul" type="xs:string"/>
                <xs:element name="wykonawca" type="xs:string"/>
                <xs:element name="wydawca" type="xs:string"/>
                <xs:element name="rok_wydania" type="xs:string"/>
                <xs:element name="czas_trwania" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== pkrausee/UG-XML/lab7/zad6.xml
<?xml version="1.0" encoding="utf-8"?>
<zamowienie numer_zamowienia="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad6.xsd">
    <adres termin_dostarczenia="1234" kraj="Polska">
        <miejsce>a</miejsce>
        <ulica>a</ulica>
        <kod_pocztowy>a</kod_pocztowy>
    </adres>
    <artykuly>
        <artykul id="1">
            <film>
                <tytul>a</tytul>
                <rezyser>a</rezyser>
                <rok_wydania>a</rok_wydania>
                <czas_trwania>a</czas_trwania>
            </film>
            <ilosc>2</ilosc>
        </artykul>
        <artykul id="2">
            <ksiazka>
                <tytul>a</tytul>
                <autor>a</autor>
                <rok_wydania>a</rok_wydania>
                <nr_wydania>a</nr_wydania>
            </ksiazka>
            <ilosc>1</ilosc>
        </artykul>
        <artykul id="3">
            <plyta>
                <tytul>a</tytul>
                <wykonawca>a</wykonawca>
                <wydawca>a</wydawca>
                <rok_wydania>a</rok_wydania>
                <czas_trwania>a</czas_trwania>
            </plyta>
            <ilosc>1</ilosc>
        </artykul>
    </artykuly>
</zamowienie>
